[theme]
base = "light"
primaryColor = "#06C755"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F7F5"
textColor = "#262730"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
